### ISSUE TITLE

        docs: project philosophy
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#1020]
New updates on head repo.
https://github.com/vitejs/vite/commit/17c63feab47d37a42220505762c7ca0ad8150482

**Comment by MH4GF** [comment]
こんにちは。
こちら翻訳担当したいです！

**Comment by MH4GF** [comment]
memo

- todo
    - guide/philosophy.md の作成
    - .vitepress/config.ts のsidebarにリンクを追加
- CONTRIBUTING.md の変更は気にしなくて良さそう？(docs-jaのCONTRIBUTING.mdとは別の内容のため)
- https://vitejs.dev/guide/philosophy.html はまだ反映されていない？

**Comment by jay-es** [comment]
@MH4GF よろしくお願いします。
`CONTRIBUTING.md` は対応しなくて大丈夫です！
