### ISSUE TITLE

        chore(deps): update dependency prettier to v3
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#1039]
New updates on head repo.
https://github.com/vitejs/vite/commit/5a56941a895fd0ffdbdbf0094336fb7f0f4099c1

**Comment by MH4GF** [comment]
docs-jaリポジトリではprettierを利用していないため、対応不要に見えました。こちらいかがでしょう？ @jay-es

**Comment by jay-es** [comment]
@MH4GF ご確認ありがとうございます:pray:
確かにこちらのリポジトリでは prettier はないので対応不要ですね。
クローズします
