### ISSUE TITLE

        docs(wasm): add sections about Node.js and module access
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#1045]
New updates on head repo.
https://github.com/vitejs/vite/commit/2c73d10ed2e18db6da892acdcfe1637b86d72599

**Comment by MH4GF** [comment]
こんばんは。
こちら翻訳担当したいです！

**Comment by jay-es** [comment]
@MH4GF ありがとうございます！よろしくお願いします！:pray:
