### ISSUE TITLE

        docs: add example for mergeConfig with a config in callback form (#14…
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#1056]
New updates on head repo.
https://github.com/vitejs/vite/commit/094b7324827940ee02c8e4a9ccae5e25c236eecd

**Comment by MH4GF** [comment]
こんにちは。
こちら翻訳担当したいです！

**Comment by MH4GF** [comment]
📝 https://github.com/vitejs/docs-ja/pull/1073 と同じファイルの変更であり、行番号のズレなどがあるため、念の為マージされてから作業する
