### ISSUE TITLE

        refactor: remove CJS ssr output format
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#1088]
New updates on head repo.
https://github.com/vitejs/vite/commit/2f60b9e9f728008f00eb5cb47155dda4f3e7be08

**Comment by MH4GF** [comment]
こんにちは。
こちら翻訳対応したいです！

**Comment by jay-es** [comment]
@MH4GF こちら後続の issue で同じファイルに変更が入っているため巻き取らせていただきます。
また次の機会にご協力お願いします:bow:

**Comment by MH4GF** [comment]
@jay-es 対応できておらずすみません 🙏🏻
