### ISSUE TITLE
In-page navigation seems doesn't work

### ISSUE THREAD

**Issue by kazuma0129** [vitejs/docs-ja#1142]
Hi team, I use this document all the time. Thank you for maintaining it. 
Now I found a little bug of some kind, could you please check it out?

In-page navigation works for English documents but does not seem to be the case for Japanese documents.
Specifically, the link in the sentence `ベースパスの高度な制御については、高度なベースパスの設定を参照してください。` on the page shown below.
- ja: https://ja.vitejs.dev/guide/build.html

As I said earlier, it seems to work for English. (`For advanced base path control, check out Advanced Base Options.`)
- en: https://vitejs.dev/guide/build.html

By the way, I don't think this problem occurs only on certain pages. This is because I found the same problem on the following page as well.
- https://ja.vitejs.dev/guide/using-plugins.html

Please let me know if there is any other information you need. Best regards.

**Comment by jay-es** [comment]
メモ:
日本語になっているリンクハッシュを `encodeURIComponent()` すれば直るがあまりきれいではない。
Vue.js ドキュメントと同じように見出しに英語のアンカーをつけ、リンクのハッシュを英語に戻すのがよいか。

該当箇所 `\]\([^)]+?#[^)]+?[^\u0000-\u007f][^)]+?\)`
27 results - 14 files

**Comment by jay-es** [comment]
@kazuma0129 こちら修正しました。
また何か気づいたことがあったらお知らせください:pray:

**Comment by kazuma0129** [comment]
@jay-es ご対応ありがとうございます！対応が早く、とても助かりました🙏
