### ISSUE TITLE
旧183 docs: typos in config page

### ISSUE THREAD

**Issue by jay-es** [vitejs/docs-ja#12]
New updates on head repo. https://github.com/vitejs/vite/commit/d1a0e7886db0bda67489f01cfbc52b46ff13e421

**Comment by jay-es** [comment]
（メモ）18-285 は翻訳済みのため対応不要。 635, 642 行目だけでよい

**Comment by takmatsukawa** [comment]
✋ やります

**Comment by jay-es** [comment]
お願いします！
