### ISSUE TITLE

        feat: preserve vite.middlewares connect instance after restarts
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#1234]
New updates on head repo.
https://github.com/vitejs/vite/commit/9474c4be279e342db2264fa9e7a8b84abb54a93e

**Comment by shuuji3** [comment]
こちらも作業中です。

ただ、原文にtypoがあったのでupstreamにPRを提出しています: https://github.com/vitejs/vite/pull/15429
