### ISSUE TITLE
ブログ記事の翻訳について

### ISSUE THREAD

**Issue by shuuji3** [vitejs/docs-ja#1258]
こんにちは。未翻訳のこちらのブログ記事 (Vite 5.0 is out! https://ja.vitejs.dev/blog/announcing-vite5.html) の翻訳をしてみたいと思っているのですが、このリポジトリではブログ記事の翻訳PRも受け付けていますか？

**Comment by jay-es** [comment]
返信遅くなりすみません。

- リリースからひと月たっていて新規性がなく翻訳する必要性が低いこと
- 今までもブログは翻訳しておらず、この記事を翻訳することで今後の記事も毎回翻訳しないといけなくなること

という理由により翻訳はしなくてもよいかなと思っております。
本リポジトリに貢献したいということであれば、英語版との差分解消の issue をお手伝いいただけると助かります :pray:

**Comment by shuuji3** [comment]
いえ、お返事ありがとうございます。たしかに今後メンテナンスしていくことを考えると少し負担になってしまいそうですね。了解しました。

差分解消のissueについては余裕があるときに見てみようと思います🙂
