### ISSUE TITLE

        docs: fix lightning css typo
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#1265]
New updates on head repo.
https://github.com/vitejs/vite/commit/f43945c1c35de34d64b2b1772b1629aba83cb476

**Comment by shuuji3** [comment]
こちらの誤字は日本語翻訳ではすでに修正されているので、このままcloseできそうです。

当該行はこちら: https://github.com/vitejs/docs-ja/blob/03921f7646c2ac91263ac3c8cdd44b27a05b51a0/guide/features.md?plain=1#L294-L294

**Comment by jay-es** [comment]
@shuuji3 ご確認ありがとうございます！
こちら close しておきます 🙇

**Comment by shuuji3** [comment]
ありがとうございます🙏🏻
