### ISSUE TITLE

        docs: add warning on Worker import with constructor limitations
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#1288]
New updates on head repo.
https://github.com/vitejs/vite/commit/3fceb14b94b12d12d47285402980f360aa4284ea

**Comment by yoshi2no** [comment]
こちら対応して良いでしょうか？

**Comment by jay-es** [comment]
@yoshi2no ありがとうございます！
ぜひよろしくお願いします :pray:
