### ISSUE TITLE
JSXサポート部分の訳出について

### ISSUE THREAD

**Issue by yudai-nkt** [vitejs/docs-ja#1296]
JSXサポートに関する記述に以下の一節がありますが，「React、または Vue で JSX を使用していない」と言われて最初に思い浮かんだのは`<div>foo</div>`ではなく`React.createElement("div", null, "foo")`などと書くことでした．

https://github.com/vitejs/docs-ja/blob/b2dc5e8fb8286c21a1534e370a953300d76076fd/guide/features.md?plain=1#L177

後ろにPreactの例が続くことや原文の"If not using JSX with React or Vue"からも分かるように，これは「React、または Vue 以外で JSX を使用している」の方が近いと思うのですがいかがでしょうか？

逐語訳により近いのは現状の訳文なので，読み違える人が他にも発生しうるかをPRなどに着手する前に皆さんの感覚を聞きたいです．

**Comment by shuuji3** [comment]
私もこちらは正しい指摘だと思います。ここでは「JSXを使用していない」場合ではなくて、JSXを使っている場合に変換後の関数を`React.createElement()`以外にどう設定するか (Preactの場合は`<div>foo</div>`を`React.createElement("div", null, "foo")`ではなく`h("div", null, "foo")`に変換されるように設定したい) という話ですよね。

**Comment by jay-es** [comment]
@yudai-nkt ありがとうございます！
確かに現状だと別の意味に伝わってしまいそうですね。

@shuuji3 英語版の PR 作成ありがとうございます！ :pray:
意味が明確になってよいと思います。

意訳禁止というわけでもないので、自分の方で修正しておきます

**Comment by yudai-nkt** [comment]
確かに英語版自体もwithoutにした方が解釈の揺れがなくていいですね．エスカレーションと日本語版の修正ありがとうございました！
