### ISSUE TITLE

        docs(features): clarify sentences about JSX usage
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#1317]
New updates on head repo.
https://github.com/vitejs/vite/commit/7dcb0ba4976c3cf30aa34e439d071c158e3ce165

**Comment by shuuji3** [comment]
#1296 の時に作ったPRなので、このままclose可能です。

**Comment by jay-es** [comment]
@shuuji3 確認ありがとうございます。close しておきます！

**Comment by shuuji3** [comment]
ありがとうございます 👍🏻
