### ISSUE TITLE
旧185 docs: config hook is async

### ISSUE THREAD

**Issue by jay-es** [vitejs/docs-ja#14]
New updates on head repo. https://github.com/vitejs/vite/commit/5c177db9597344b8151c8e421ddbced36c4151c7

**Comment by takmatsukawa** [comment]
✋ やります

**Comment by jay-es** [comment]
念のため、先行の Issue が完了してからアサインさせていただきます:bow:

**Comment by jay-es** [comment]
よろしくお願いします！
