### ISSUE TITLE

        chore(deps): remove unused deps
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#1437]
New updates on head repo.
https://github.com/vitejs/vite/commit/5a457454bfee1892b0d58c4b1c401cfb15986097

**Comment by shuuji3** [comment]
`feed`パッケージを`package.json`から`docs/package.json`に移動するという変更なので、このリポジトリでは修正は必要なさそうです。(上のコミットは無視してください)

**Comment by jay-es** [comment]
@shuuji3 ありがとうございます！
このままクローズしておきます :pray:
