### ISSUE TITLE

        docs: fix typos
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#1465]
New updates on head repo.
https://github.com/vitejs/vite/commit/fc049719053a3051179aa1e5f46889f2ee2832b1

**Comment by shuuji3** [comment]
こちらも英語の文法上の細かい間違いの修正なので、日本語訳では修正は必要なさそうです！

**Comment by jay-es** [comment]
@shuuji3 ご確認ありがとうございます！ 🙏 
クローズしておきます！
