### ISSUE TITLE

        docs(server-options): fix RegEx -> RegExp
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#1515]
New updates on head repo.
https://github.com/vitejs/vite/commit/11644f4e378e30f839d21f89807a32cc196dd78b

**Comment by shuuji3** [comment]
日本語ではすでに「正規表現」と翻訳されている箇所だったので、こちらのissueはスキップして問題なさそうです。

対応する日本語翻訳→https://github.com/shuuji3/vite-docs-ja/blob/main/config/server-options.md?plain=1#L111-L111

**Comment by jay-es** [comment]
@shuuji3 ありがとうございます！
close しておきます 🙏
