### ISSUE TITLE

        feat: Environment API
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#1534]
New updates on head repo.
https://github.com/vitejs/vite/commit/242f550eb46c93896fca6b55495578921e29a8af

**Comment by jay-es** [comment]
差分が大きいので小分けで対応するのがよいか
- `/changes/`
- `/guide/api-environment`
  - `/guide/api-vite-runtime` 削除
- `/guide/migration`
- その他

**Comment by jay-es** [comment]
4つに分けたのでこの issue は完了
