### ISSUE TITLE
旧191 chore: update create-vite commands

### ISSUE THREAD

**Issue by jay-es** [vitejs/docs-ja#20]
New updates on head repo. https://github.com/vitejs/vite/commit/eb39853479d6dfd6bd0e63ad07a44e8614986866

**Comment by takmatsukawa** [comment]
翻訳やりたいです
細かい修正でも、1Issue 1PRとして分けていますか？

**Comment by jay-es** [comment]
@takmatsukawa はい、PR は分けていただけるとレビューがしやすいです:pray:
