### ISSUE TITLE
旧192 feat: enable usage of function as library fileName, close #3585

### ISSUE THREAD

**Issue by jay-es** [vitejs/docs-ja#21]
New updates on head repo. https://github.com/vitejs/vite/commit/772b2f73b0da08181a7cc29e0eb50073ff3cc464

**Comment by takmatsukawa** [comment]
翻訳やりたいです

**Comment by jay-es** [comment]
こちら翻訳は別で進めるつもりでしたので、差分の取り込みのみお願いします:bow:

**Comment by jay-es** [comment]
@takmatsukawa こちら翻訳は別で進めるつもりでしたので、差分の取り込みのみお願いします:bow:
ちなみに、こちらのリポジトリには packages ディレクトリはないので、docs/ の2ファイルのみで大丈夫です
