### ISSUE TITLE
旧194 chore(docs): add colons to api pages

### ISSUE THREAD

**Issue by jay-es** [vitejs/docs-ja#22]
New updates on head repo. https://github.com/vitejs/vite/commit/757cc6b9fd8d6315ff88e57d406c6abb0d43aa1b

**Comment by jay-es** [comment]
メモ: api-plugin.md は #7 で対応済みなので、api-javascript.md のみ修正

**Comment by takmatsukawa** [comment]
やりたいです

**Comment by jay-es** [comment]
よろしくお願いします！
