### ISSUE TITLE

        docs: update preview port
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#297]
New updates on head repo.
https://github.com/vitejs/vite/commit/c70dc6a1cf853414a9ece470f6ac76ec4d7dff34

**Comment by keita-hino** [comment]
こちら対応しても良いでしょうか👀

**Comment by jay-es** [comment]
@keita-hino ありがとうございます！
こちらは #296 で変更された箇所に対する修正なので、#296 も同時に対応していただけますか:pray:

**Comment by keita-hino** [comment]
@jay-es 
承知しました！
併せて修正します💪
