### ISSUE TITLE
訳の修正: Guide - Hot Module Deployment

### ISSUE THREAD

**Issue by dayflower** [vitejs/docs-ja#332]
https://github.com/vitejs/docs-ja/blob/a567d176008756b95efe6adecddd474bc0207a18/guide/features.md?plain=1#L33

こちら

```markdown
Vite は `.ts` ファイルに対してのみ変換を実行し、型チェックは **実行しません**。
```

となっておりますが、原文が

https://github.com/vitejs/vite/blob/ed4d19103e2daec4368f2e143f4207837df6b27f/docs/guide/features.md?plain=1#L33

```markdown
Vite only performs transpilation on `.ts` files and does **NOT** perform type checking.
```

ですので、たとえば

```markdown
Vite は `.ts` ファイルに対して変換のみおこない、型チェックは **実行しません**。
```

のような表現のほうが適切だと思います。

**Comment by jay-es** [comment]
ありがとうございます！:pray:
