### ISSUE TITLE

        docs: exhibit defineConfig
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#34]
New updates on head repo.
https://github.com/vitejs/vite/commit/cd44691b391dba5b7c355ad08849245e8d777810

**Comment by jay-es** [comment]
`guide/backend-integration.md` は #45 で対応済み

**Comment by bhbs** [comment]
こちら対応してもよろしいでしょうか？🙏

**Comment by jay-es** [comment]
お願いします！
Issue 12~19 が先のコミットに当たるので、念のためデグレなどがないか確認お願いします:pray:

**Comment by bhbs** [comment]
typoがあったので本体にPR中
https://github.com/vitejs/vite/pull/4445
