### ISSUE TITLE

        docs: vite only replace `__dirname`, `__filename`, `import.meta.url` …
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#359]
New updates on head repo.
https://github.com/vitejs/vite/commit/f44859379277b7a3e99529be275022733dc69ef1

**Comment by hiro-lapis** [comment]
こちら対応してもよろしいでしょうか？

**Comment by hiro-lapis** [comment]
@jay-es 
プルリク送らせてもらいました!
都合よろしいときにレビューをおねがいします🙇‍♂️
