### ISSUE TITLE

        docs: classic worker
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#360]
New updates on head repo.
https://github.com/vitejs/vite/commit/4e0b61593a0eba97a901f996619c5e1aae4a7b68

**Comment by hiro-lapis** [comment]
こちら対応させてもらってもいいでしょうか？

**Comment by jay-es** [comment]
@hiro-lapis よろしくお願いします！:pray:

**Comment by hiro-lapis** [comment]
@jay-es
プルリク送らせてもらいました!
都合よろしいときにレビューをおねがいします🙇‍♂️
