### ISSUE TITLE

        feat(dev): expose APIs for client-server communication
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#363]
New updates on head repo.
https://github.com/vitejs/vite/commit/e29ea8ea37c295bc500a2321b831f65a893ec750

**Comment by hiro-lapis** [comment]
こちら対応させてもらってもいいでしょうか？

また、オリジナルの変更のうち対応すべきなのはmdファイル
`docs/guide/api-hmr.md`
`docs/guide/api-plugin.md`
の2つで合ってますか？

**Comment by jay-es** [comment]
@hiro-lapis お願いします:pray:
変更は `docs/` の2ファイルでOKです！
