### ISSUE TITLE

        refactor: deprecate polyfillDynamicImport
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#37]
New updates on head repo.
https://github.com/vitejs/vite/commit/318cb43380ed05c1f5490f6127ca358711c3b764

**Comment by jay-es** [comment]
`guide/backend-integration.md` は #45 で対応済み

**Comment by bhbs** [comment]
こちら対応してもよろしいでしょうか？🙏

**Comment by jay-es** [comment]
お願いします！
Issue 12~19 が先のコミットに当たるので、念のためデグレなどがないか確認お願いします:pray:
