### ISSUE TITLE

        docs: mention `process.env` for config env vars
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#391]
New updates on head repo.
https://github.com/vitejs/vite/commit/434bb5c05bce8a376bde50100a1466072d5e3624

**Comment by hiro-lapis** [comment]
@jay-es 
こちら対応させてもらってもいいでしょうか？

**Comment by jay-es** [comment]
@hiro-lapis よろしくお願いします！

**Comment by hiro-lapis** [comment]
@jay-es 
着手する前に気付けずすみませんが、対応について相談させてください。

ISSUEの元となったセクション(`Environment Variables`)の翻訳が、
#339 で行われており、まだ`main`に取り込まれていません。

なので、#339 からブランチを切る&マージ先も#339 に向ける形で対応してもいいでしょうか？

**Comment by jay-es** [comment]
@hiro-lapis はい、339をベースにして、PRも339に向けてください。
おそらく別の未マージPRがあり行がずれているので、そこは気にせず進めてください:pray:

**Comment by hiro-lapis** [comment]
@jay-es 

プルリク立てさせてもらいました。
マージ先の関係で jay-esさんのリポジトリにプルリクが表示されています。
よろしくお願いします🙇‍♂️
https://github.com/jay-es/vitejs-docs-ja/pull/1
