### ISSUE TITLE

        docs: explain skipLibCheck
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#393]
New updates on head repo.
https://github.com/vitejs/vite/commit/788d2ec1dc9853be4ecdef67d1a458a2b46ec9bf

**Comment by hiro-lapis** [comment]
こちら対応させてもらってもいいでしょうか？

**Comment by jay-es** [comment]
@hiro-lapis よろしくお願いします！

**Comment by hiro-lapis** [comment]
すみません、
ISSUEの紐付けを間違えてしまいました。

このISSUEは #398 で対応させてもらったので、このISSUEをクローズさせてもらえないでしょうか？
