### ISSUE TITLE

        docs: make it clear that array format can only be used for inline pos…
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#397]
New updates on head repo.
https://github.com/vitejs/vite/commit/9c6501d9c363eaa3c1e7708d531fb2a92b633db6

**Comment by hiro-lapis** [comment]
こちらも対応させていただいてもいいでしょうか？

**Comment by jay-es** [comment]
@hiro-lapis よろしくお願いします！
#352 は自分でレビューして大丈夫そうだったのでマージしました。main からブランチ作成してください:pray:
