### ISSUE TITLE

        docs(api-hmr): update hmr hot type
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#399]
New updates on head repo.
https://github.com/vitejs/vite/commit/72abe488b5ce52d21977c9ba35d6c590e47dbe05

**Comment by hiro-lapis** [comment]
こちら対応させてもらってもいいでしょうか？
また、コミット内容から考えて、ドキュメント内サンプルコードを更新のみ対応すればOK、で認識合ってるでしょうか？

**Comment by jay-es** [comment]
よろしくお願いします。
コードブロックの差分反映で問題ないです
