### ISSUE TITLE

        docs: `server.origin` config trailing slash (fix #6622)
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#404]
New updates on head repo.
https://github.com/vitejs/vite/commit/5c1ee5abf987e25bd39d5af8013ed907a33d4d14

**Comment by hiro-lapis** [comment]
こちら対応させてもらってもいいでしょうか？
また、本家のコミットの内、`src/node`配下のtsファイルについては対応しないで大丈夫という認識で合ってるでしょうか？

**Comment by jay-es** [comment]
@hiro-lapis よろしくお願いします。
`docs/` の反映のみで問題ないです:pray:
