### ISSUE TITLE

        docs: grammar fix in getting started guide
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#408]
New updates on head repo.
https://github.com/vitejs/vite/commit/aebaf66cdb5bd9c39225462621e6f55275790463

**Comment by hiro-lapis** [comment]
翻訳ページを確認しましたが、日本語なので現在の訳のままで大丈夫と思いましたが、どうでしょうか？
https://github.com/vitejs/docs-ja/blob/main/guide/index.md

**Comment by jay-es** [comment]
@hiro-lapis ありがとうございます。対応なしで大丈夫そうなので Close します:pray:
