### ISSUE TITLE
Migration from v1 の翻訳

### ISSUE THREAD

**Issue by jay-es** [vitejs/docs-ja#41]
`gude/migration.md` の翻訳をお願いします。

はじめに翻訳ガイドをご一読ください（PR 中の内容ですが注意事項が追加されています）
https://github.com/vitejs/docs-ja/blob/28ad51c26084ff01fb80a96d76ca2105a5efe604/CONTRIBUTING.md

- ページタイトルは #26 で翻訳済みなので、変更しなくて OK です。
- ページ翻訳中に Vite 本体からの変更が反映されている場合があるので、PR 作成前に vitejs/docs-ja の main ブランチをマージして差分が発生していないかご確認お願いいたします:pray:
- 過去の実績ですと1ページの翻訳は数日～ひと月あたりが目安です。やむを得ず遅くなりそうな場合はご一報いただけると助かります:pray:

**Comment by takmatsukawa** [comment]
✋  やりたいです

**Comment by jay-es** [comment]
よろしくお願いします！
