### ISSUE TITLE

        refactor: remove deprecated api for 3.0
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#411]
New updates on head repo.
https://github.com/vitejs/vite/commit/b5c370941bb36bdb420433ca16cea9c2402b9810

**Comment by hiro-lapis** [comment]
こちら対応させてもらってもいいでしょうか？

**Comment by jay-es** [comment]
@hiro-lapis 余分なスペース削除もよろしくお願いします！
