### ISSUE TITLE

        feat: new hook `configurePreviewServer`
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#421]
New updates on head repo.
https://github.com/vitejs/vite/commit/20ea9999765ea372c20acc39e05cd81b98c9f6fe

**Comment by hiro-lapis** [comment]
こちら対応させてもらってもいいでしょうか？

**Comment by jay-es** [comment]
@hiro-lapis ありがとうございます！
次回からは「対応します」みたいな感じで大丈夫です:pray:

**Comment by hiro-lapis** [comment]
承知しました。
今度ともよろしくおねがいします🙌
