### ISSUE TITLE

        docs: update for default target change
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#439]
New updates on head repo.
https://github.com/vitejs/vite/commit/e68c25cf464428fb42e622fd3749f0daf1b943ab

**Comment by hiro-lapis** [comment]
@jay-es 
こちら対応にあたって相談させてください🙇‍♂️
`docs/guide/assets.md`の反映をするにあたって、jay-esさんの対応してくださったブランチ（#378 ）の反映が必要です。

私の方でも訳を確認させてもらったところ大丈夫そうだったので、#378 をマージしていただくことは可能でしょうか？

**Comment by jay-es** [comment]
@hiro-lapis ありがとうございます。古い PR を確認してすべてマージしました:bow:
