### ISSUE TITLE

        docs: use vitepress next
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#441]
New updates on head repo.
https://github.com/vitejs/vite/commit/52539011bc6350e376ed15eca4c408579deb363d

**Comment by hiro-lapis** [comment]
@jay-es 
相談です。
一応反映するプルリクを作成したのですが、こちらのISSUEは対応しなくてもいいでしょうか？

私の方で確認した限り、このISSUEで対応すべき差分が`docs/index.md`のTODOコメントだけなのですが、
#447 で上記TODOコメントも消えます。
わざわざこのISSUEの対応をしなくてもいいのかな、、、と思っています。

**Comment by jay-es** [comment]
@hiro-lapis PR にもコメントしましたが、こちらは VitePress アップデートが主な内容だと思うので、`.md` 以外も一通り対応お願いします:pray:

**Comment by hiro-lapis** [comment]
失礼しました🙇‍♂️
VitePressの変更含め対応させてもらいます！
