### ISSUE TITLE

        docs: cleanup changes
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#561]
New updates on head repo.
https://github.com/vitejs/vite/commit/07aef1b4c02a64732b31b00591d2d9d9c8025aab

**Comment by jay-es** [comment]
先に #641 で https://github.com/vitejs/vite/commit/8c528673ed731cdac9882cbf502bc40b382d5b65 を対応したので、`guide/ssr.md` の行番号が変わっています

**Comment by sapphi-red** [comment]
こちら対応します🦕
