### ISSUE TITLE

        docs: migration from v3 guide
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#789]
New updates on head repo.
https://github.com/vitejs/vite/commit/e57ebba5466c70832e1c2bec0838d52fb4625cbe

**Comment by jay-es** [comment]
いっしょにメニューも修正する
https://github.com/vitejs/vite/commit/897f69f9b6fd3726a93c35a3a57c8cab8379711f#diff-3def678deb1b1d5a53948eb8491817dde4dc881e032e785fc61cc93d334eefcdR241

**Comment by jay-es** [comment]
対応します
