### ISSUE TITLE
旧179 docs: clarify CommonJS with `optimizeDeps.exclude`

### ISSUE THREAD

**Issue by jay-es** [vitejs/docs-ja#8]
New updates on head repo. https://github.com/vitejs/vite/commit/8fa75b5f9ff3730270d0793e860019b9aa4577de

**Comment by takmatsukawa** [comment]
翻訳やりたいです

**Comment by jay-es** [comment]
お願いします！

**Comment by takmatsukawa** [comment]
差分の反映用Issueがまた増えてますね...これはもしや、結構なペースで発生するものですか？ @jay-es

**Comment by jay-es** [comment]
@takmatsukawa ペースはまちまちで、5日空くこともあれば数時間の場合もありますね。
平均すると、最近は1日1件未満だと思います。

**Comment by takmatsukawa** [comment]
なるほど、ちょっと安心しました。が、Gitマージくらいの賢さで差分自動反映してほしくもある 🤔
