### ISSUE TITLE
旧180 feat: allow passing options to rollupjs dynamic import vars plugin (#…

### ISSUE THREAD

**Issue by jay-es** [vitejs/docs-ja#9]
New updates on head repo. https://github.com/vitejs/vite/commit/5507b4c912d2e0e36e63488f5db8e9d1bb0a80f6

**Comment by takmatsukawa** [comment]
翻訳やりたいです

**Comment by jay-es** [comment]
お願いします！

**Comment by takmatsukawa** [comment]
差分の前後は未翻訳ですが、ファイル前半は翻訳済みのようです。差分のところだけ翻訳しちゃって問題ないですか？

**Comment by jay-es** [comment]
はい、OKです。お願いします！
