### ISSUE TITLE

        docs: document /index.html as importer during dev
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#963]
New updates on head repo.
https://github.com/vitejs/vite/commit/21dd28dd648b6d043eaad2f31efdd379e5134635

**Comment by jay-es** [comment]
@kotaesaki ありがとうございます！ぜひよろしくお願いします。
流れについてはこちらをご確認ください。
https://github.com/vitejs/docs-ja/blob/main/CONTRIBUTING.md

**Comment by kotaesaki** [comment]
@jay-es 
すいません、[ドキュメント](https://github.com/vitejs/docs-ja/blob/main/CONTRIBUTING.md)の確認漏れで最新のISSUEからやっておりました。
PR出してから気づいてしまい大変申し訳ないです🙇

**Comment by jay-es** [comment]
@kotaesaki こちらの issue が前の issue とコンフリクトしないことを確認してあるので大丈夫です:+1:
