### ISSUE TITLE

        docs: cross drive links troubleshooting guide
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#980]
New updates on head repo.
https://github.com/vitejs/vite/commit/2497756b2f3dd5ed498e4b8b01958e76be26cc2d

**Comment by MH4GF** [comment]
はじめまして。こちらの翻訳を担当したいです！
[CONTRIBUTING.md](https://github.com/vitejs/docs-ja/blob/main/CONTRIBUTING.md)を確認済みです。

**Comment by jay-es** [comment]
@MH4GF ありがとうございます！
ぜひよろしくお願いします:pray:
