### ISSUE TITLE

        docs: accessing the server on WSL2 from your LAN
    

### ISSUE THREAD

**Issue by kiaking** [vitejs/docs-ja#981]
New updates on head repo.
https://github.com/vitejs/vite/commit/2872d5520a1a088a89effb155edf59d776a3ced3

**Comment by MH4GF** [comment]
こんにちは。
こちら翻訳担当したいです！

**Comment by jay-es** [comment]
@MH4GF ありがとうございます！
よろしくお願いします:pray:
